// change css on checkbox selection
let checkbox = document.getElementById('checkbox');

let boxInterval = document.getElementById('interval');

checkbox.addEventListener('click', function handleClick() {
  if (checkbox.checked) { boxInterval.style.display = 'block';  } 
  else {  boxInterval.style.display = 'none';  }
});



let interval;

document.getElementById("inputSearch").addEventListener("change",()=>{ 
    let select = document.getElementById("inputSearch");
    let count = select.options[select.selectedIndex].value * 1;
    document.getElementById("pTag").textContent = count;

});


document.getElementById("buttonStart").addEventListener("click",async () => {

    // change css of button on each click
    document.getElementById("buttonStart").style.backgroundColor = "rgb(247, 159, 255)";
    setTimeout(()=>{ document.getElementById("buttonStart").style.backgroundColor = "rgb(255, 255, 255)"; },1500);


    // if interval already created clear it
    if(interval){ clearInterval(interval); }

    let [currTab] = await chrome.tabs.query({active:true, currentWindow:true});


    // "duration" is "waiting after each search" AND "durationBing" is "waiting after bing.com opened"
    let selectDuration = document.getElementById("input");
    let duration = selectDuration.options[selectDuration.selectedIndex].value*1000;
    let durationBing = 0;
    if(document.getElementById('checkbox').checked){
        let selectDurationBing = document.getElementById("interval");
        durationBing = selectDurationBing.options[selectDurationBing.selectedIndex].value*1000;
    }

    // Number of searches
    let select = document.getElementById("inputSearch");
    let count = select.options[select.selectedIndex].value * 1;

    interval = setInterval(()=>{ 

        // open bing.com first if checkbox is selected and wait for "durationBing" mili sec
        if(document.getElementById('checkbox').checked){
            let selectDurationBing = document.getElementById("interval");
            durationBing = selectDurationBing.options[selectDurationBing.selectedIndex].value*1000;
            chrome.tabs.update({active: true, url: "https://www.bing.com/"});
            console.log("bing opened");
        }
        
        // inject JS to active tab console after "durationBing" mili sec
        setTimeout(()=>{

            chrome.scripting.executeScript({
                target : { tabId : currTab.id },
                func : runOnTab,
                args: [count]
            });
            console.log("js injected");
            // updating count of searches left
            count--;
            document.getElementById("pTag").textContent = count;
            if(count === -1){ 
                // let url = chrome.runtime.getURL('beep.mp3');
                // let sound = new Audio(url); 
                //sound.play();
                clearInterval(interval); 
            }


        }, durationBing);
        

    },duration + durationBing);

});




function runOnTab(count){
   

    let itemSer = [
        "java",
        "What is Java and what are its advantages?",
        "What is the difference between JDK, JRE, and JVM?",
        "What is an object in Java?",
        "What is the difference between a class and an object?",
        "What is inheritance and how does it work in Java?",
        "What is polymorphism in Java?",
        "What are the different types of access modifiers in Java?",
        "What is the difference between an interface and an abstract class?",
        "What is a constructor in Java?",
        "What is the difference between method overloading and method overriding?",
        "What is a package in Java?",
        "What is a static method in Java?",
        "What is the difference between static and non-static variables?",
        "What is an exception in Java?",
        "What is a try-catch block in Java?",
        "What is the purpose of the finally block in a try-catch-finally statement?",
        "What is a RuntimeException?",
        "What is the difference between checked and unchecked exceptions?",
        "What is the difference between a while loop and a do-while loop?",
        "What is a for loop in Java?",
        "What is a switch statement in Java?",
        "What is a break statement in Java?",
        "What is a continue statement in Java?",
        "What is a method in Java?",
        "What is recursion in Java?",
        "What is the difference between the == operator and the equals() method?",
        "What is a StringBuilder in Java?",
        "What is the difference between StringBuffer and StringBuilder?",
        "What is a Java interface?",
        "What is the difference between an interface and a class?",
        "What is an abstract class in Java?",
        "What is a nested class in Java?",
        "What is a static nested class in Java?",
        "What is an inner class in Java?",
        "What is a local inner class in Java?",
        "What is a method-local inner class in Java?",
        "What is a lambda expression in Java?",
        "What is the purpose of the stream API in Java?",
        "What is the difference between parallel and sequential streams in Java?",
        "What is a synchronized method in Java?",
        "What is a synchronized block in Java?",
        "What is a thread in Java?",
        "What is the difference between a process and a thread?",
        "What is the purpose of the wait(), notify(), and notifyAll() methods in Java?",
        "What is a deadlock in Java?",
        "What is the purpose of the synchronized keyword in Java?",
        "What is the purpose of the volatile keyword in Java?",
        "javaScript",
        "What is JavaScript and what are its advantages?",
        "What is the difference between JavaScript and Java?",
        "What is an object in JavaScript?",
        "What is the difference between a primitive type and an object in JavaScript?",
        "What is an array in JavaScript?",
        "What is the difference between null and undefined in JavaScript?",
        "What is the scope chain in JavaScript?",
        "What is hoisting in JavaScript?",
        "What is a closure in JavaScript?",
        "What is the difference between var, let, and const in JavaScript?",
        "What is a callback function in JavaScript?",
        "What is a higher-order function in JavaScript?",
        "What is the difference between synchronous and asynchronous code in JavaScript?",
        "What is a promise in JavaScript?",
        "What is async/await in JavaScript?",
        "What is an arrow function in JavaScript?",
        "What is a template literal in JavaScript?",
        "What is the difference between == and === in JavaScript?",
        "What is the typeof operator in JavaScript?",
        "What is the instanceof operator in JavaScript?",
        "What is the ternary operator in JavaScript?",
        "What is a switch statement in JavaScript?",
        "What is a for loop in JavaScript?",
        "What is a while loop in JavaScript?",
        "What is a do-while loop in JavaScript?",
        "What is the difference between break and continue in JavaScript?",
        "What is the spread operator in JavaScript?",
        "What is the rest operator in JavaScript?",
        "What is destructuring in JavaScript?",
        "What is the Map object in JavaScript?",
        "What is the Set object in JavaScript?",
        "What is the filter() method in JavaScript?",
        "What is the reduce() method in JavaScript?",
        "What is the find() method in JavaScript?",
        "What is the some() method in JavaScript?",
        "What is the every() method in JavaScript?",
        "What is the forEach() method in JavaScript?",
        "What is the bind() method in JavaScript?",
        "What is the call() method in JavaScript?",
        "What is the apply() method in JavaScript?",
        "What is the prototype in JavaScript?",
        "What is prototypal inheritance in JavaScript?",
        "What is the class syntax in JavaScript?",
        "What is the new keyword in JavaScript?",
        "What is the this keyword in JavaScript?",
        "What is the window object in JavaScript?",
        "What is the document object in JavaScript?",
        "What is event bubbling in JavaScript?",
        "What is event capturing in JavaScript?",
        "What is an event listener in JavaScript?",
        "What is the difference between onclick and addEventListener in JavaScript?",
        "mySql",
        "What is MySQL and what are its advantages?",
        "What is the difference between SQL and MySQL?",
        "What is a database in MySQL?",
        "What is a table in MySQL?",
        "What is a primary key in MySQL?",
        "What is a foreign key in MySQL?",
        "What is a unique key in MySQL?",
        "What is a composite key in MySQL?",
        "What is normalization in MySQL?",
        "What is denormalization in MySQL?",
        "What is a query in MySQL?",
        "What is a subquery in MySQL?",
        "What is a join in MySQL?",
        "What is an inner join in MySQL?",
        "What is a left join in MySQL?",
        "What is a right join in MySQL?",
        "What is a full outer join in MySQL?",
        "What is a cross join in MySQL?",
        "What is a self-join in MySQL?",
        "What is a union in MySQL?",
        "What is a view in MySQL?",
        "What is a stored procedure in MySQL?",
        "What is a trigger in MySQL?",
        "What is an index in MySQL?",
        "What is a clustered index in MySQL?",
        "What is a non-clustered index in MySQL?",
        "What is a unique index in MySQL?",
        "What is a full-text index in MySQL?",
        "What is a composite index in MySQL?",
        "What is a covering index in MySQL?",
        "What is a transaction in MySQL?",
        "What is ACID in MySQL?",
        "What is isolation in MySQL?",
        "What is a lock in MySQL?",
        "What is a deadlock in MySQL?",
        "What is replication in MySQL?",
        "What is sharding in MySQL?",
        "What is partitioning in MySQL?",
        "What is a backup in MySQL?",
        "What is a restore in MySQL?",
        "What is a dump in MySQL?",
        "What is a load in MySQL?",
        "What is MySQL Workbench?",
        "What is phpMyAdmin?",
        "What is the difference between InnoDB and MyISAM in MySQL?",
        "What is the difference between CHAR and VARCHAR in MySQL?",
        "What is the difference between DATE and DATETIME in MySQL?",
        "What is the difference between GROUP BY and ORDER BY in MySQL?",
        "What is the difference between TRUNCATE and DELETE in MySQL?",
        "What is the difference between UNION and UNION ALL in MySQL?",
        "html & css", 
        "What is HTML and what are its basic elements?",
        "What is the difference between HTML and XHTML?",
        "What is CSS and what are its advantages?",
        "What is the box model in CSS?",
        "What is the difference between padding and margin in CSS?",
        "What is the difference between display: none and visibility: hidden in CSS?",
        "What is the difference between inline and block elements in HTML and CSS?",
        "What is the difference between a class and an ID in HTML and CSS?",
        "What is the difference between the <div> and <span> elements in HTML?",
        "What is the difference between the <input> and <textarea> elements in HTML?",
        "What is the difference between a <table> and a <div> in HTML?",
        "What is the difference between the <img> and <picture> elements in HTML?",
        "What is semantic HTML?",
        "What are HTML meta tags?",
        "What is the role of the <head> element in HTML?",
        "What is the role of the <body> element in HTML?",
        "What is the difference between a <section> and an <article> element in HTML?",
        "What is the difference between a <header> and a <footer> element in HTML?",
        "What is the difference between a <nav> and an <aside> element in HTML?",
        "What is the role of the <form> element in HTML?",
        "What is the difference between the <ol> and <ul> elements in HTML?",
        "What is the role of the <label> element in HTML?",
        "What is the role of the <button> element in HTML?",
        "What is the difference between the <strong> and <em> elements in HTML?",
        "What is the role of the <a> element in HTML?",
        "What are the different types of selectors in CSS?",
        "What is the difference between an ID selector and a class selector in CSS?",
        "What is the cascade in CSS?",
        "What is the difference between a child selector and a descendant selector in CSS?",
        "What is the difference between padding and margin in CSS?",
        "What is the difference between inline and block elements in CSS?",
        "What is the difference between position: absolute and position: relative in CSS?",
        "What is the difference between the float and clear properties in CSS?",
        "What is the difference between the display: inline and display: inline-block properties in CSS?",
        "What is the difference between the visibility and opacity properties in CSS?",
        "What is the difference between the width and max-width properties in CSS?",
        "What is the role of the z-index property in CSS?",
        "What is the role of the background property in CSS?",
        "What is the difference between the box-shadow and text-shadow properties in CSS?",
        "What is the difference between the margin and padding properties in CSS?",
        "What is the difference between the border-collapse and border-spacing properties in CSS?",
        "What is the role of the @media rule in CSS?",
        "What is the difference between a relative and absolute URL in HTML?",
        "What is the role of the alt attribute in the <img> element?",
        "What is the difference between the title and alt attributes in the <img> element?",
        "What is the role of the href attribute in the <a> element?",
        "What is the role of the rel attribute in the <a> element?",
        "What is the role of the target attribute in the <a> element",
        "time complexity",
        "What is time complexity?",
        "What is big O notation?",
        "What is the worst-case time complexity of linear search?",
        "What is the worst-case time complexity of binary search?",
        "What is the worst-case time complexity of bubble sort?",
        "What is the worst-case time complexity of selection sort?",
        "What is the worst-case time complexity of insertion sort?",
        "What is the worst-case time complexity of merge sort?",
        "What is the worst-case time complexity of quicksort?",
        "What is the worst-case time complexity of heap sort?",
        "What is the worst-case time complexity of radix sort?",
        "What is the worst-case time complexity of counting sort?",
        "What is the worst-case time complexity of bucket sort?",
        "What is the difference between O(1), O(log n), O(n), O(n log n), O(n^2), and O(2^n)?",
        "What is the best-case time complexity of an algorithm?",
        "What is the average-case time complexity of an algorithm?",
        "What is the difference between time complexity and space complexity?",
        "What is the difference between worst-case and average-case time complexity?",
        "What is the difference between a stable and unstable sorting algorithm?",
        "What is an in-place sorting algorithm?",
        "What is an out-of-place sorting algorithm?",
        "What is the difference between a comparison-based and non-comparison-based sorting algorithm?",
        "What is the difference between a stable and unstable sorting algorithm?",
        "What is the difference between a deterministic and non-deterministic algorithm?",
        "What is the difference between a brute force and an optimized algorithm?",
        "What is the difference between a greedy algorithm and a dynamic programming algorithm?",
        "What is the difference between a breadth-first search and a depth-first search?",
        "What is the time complexity of a nested loop?",
        "What is the time complexity of a loop with a constant number of iterations?",
        "What is the time complexity of a loop with a variable number of iterations?",
        "What is the time complexity of a recursive algorithm?",
        "What is the time complexity of a divide-and-conquer algorithm?",
        "What is the time complexity of a backtracking algorithm?",
        "What is the time complexity of a branch-and-bound algorithm?",
        "What is the time complexity of a randomized algorithm?",
        "What is the time complexity of a parallel algorithm?",
        "What is the time complexity of a sequential algorithm?",
        "What is the time complexity of a sequential algorithm with parallelism?",
        "What is the time complexity of a parallel algorithm with sequentialism?",
        "What is the time complexity of an algorithm with pipelining?",
        "What is the time complexity of an algorithm with multitasking?",
        "What is the time complexity of an algorithm with multiprocessing?",
        "What is the time complexity of an algorithm with multithreading?",
        "What is the time complexity of an algorithm with distributed processing?",
        "What is the time complexity of an algorithm with cloud computing?",
        "What is the time complexity of an algorithm with quantum computing?",
        "What is the difference between classical and quantum computing in terms of time complexity?",
        "What is the time complexity of an algorithm with machine learning?",
        "What is the time complexity of an algorithm with deep learning?",
        "space complexity",
        "What is space complexity?",
        "What is the difference between time complexity and space complexity?",
        "What is the worst-case space complexity of linear search?",
        "What is the worst-case space complexity of binary search?",
        "What is the worst-case space complexity of bubble sort?",
        "What is the worst-case space complexity of selection sort?",
        "What is the worst-case space complexity of insertion sort?",
        "What is the worst-case space complexity of merge sort?",
        "What is the worst-case space complexity of quicksort?",
        "What is the worst-case space complexity of heap sort?",
        "What is the worst-case space complexity of radix sort?",
        "What is the worst-case space complexity of counting sort?",
        "What is the worst-case space complexity of bucket sort?",
        "What is the difference between O(1), O(log n), O(n), O(n log n), O(n^2), and O(2^n) in terms of space complexity?",
        "What is the best-case space complexity of an algorithm?",
        "What is the average-case space complexity of an algorithm?",
        "What is the difference between worst-case and average-case space complexity?",
        "What is the difference between an in-place and out-of-place algorithm in terms of space complexity?",
        "What is a space-efficient algorithm?",
        "What is a space-optimized algorithm?",
        "What is the difference between space efficiency and space optimization?",
        "What is the space complexity of a nested loop?",
        "What is the space complexity of a loop with a constant number of iterations?",
        "What is the space complexity of a loop with a variable number of iterations?",
        "What is the space complexity of a recursive algorithm?",
        "What is the space complexity of a divide-and-conquer algorithm?",
        "What is the space complexity of a backtracking algorithm?",
        "What is the space complexity of a branch-and-bound algorithm?",
        "What is the space complexity of a randomized algorithm?",
        "What is the space complexity of a parallel algorithm?",
        "What is the space complexity of a sequential algorithm?",
        "What is the space complexity of a sequential algorithm with parallelism?",
        "What is the space complexity of a parallel algorithm with sequentialism?",
        "What is the space complexity of an algorithm with pipelining?",
        "What is the space complexity of an algorithm with multitasking?",
        "What is the space complexity of an algorithm with multiprocessing?",
        "What is the space complexity of an algorithm with multithreading?",
        "What is the space complexity of an algorithm with distributed processing?",
        "What is the space complexity of an algorithm with cloud computing?",
        "What is the space complexity of an algorithm with quantum computing?",
        "What is the difference between classical and quantum computing in terms of space complexity?",
        "What is the space complexity of an algorithm with machine learning?",
        "What is the space complexity of an algorithm with deep learning?",
        "What is the difference between a space complexity of O(1) and O(n)?",
        "What is the difference between a space complexity of O(n) and O(n^2)?",
        "What is the difference between a space complexity of O(n) and O(log n)?",
        "What is the difference between a space complexity of O(n) and O(n log n)?",
        "What is the difference between a space complexity of O(n) and O(2^n)?",
        "algorithm",
        "What is an algorithm?",
        "What is the difference between an algorithm and a program?",
        "What is the difference between a recursive and an iterative algorithm?",
        "What is the difference between a greedy and a dynamic programming algorithm?",
        "What is the difference between a sequential and a parallel algorithm?",
        "What is the difference between an exact and an approximate algorithm?",
        "What is the difference between an online and an offline algorithm?",
        "What is the difference between a deterministic and a randomized algorithm?",
        "What is the difference between a static and a dynamic algorithm?",
        "What is the difference between a centralized and a decentralized algorithm?",
        "What is the difference between a synchronous and an asynchronous algorithm?",
        "What is the difference between a single-core and a multi-core algorithm?",
        "What is the difference between a linear and a nonlinear algorithm?",
        "What is the difference between a scalable and a non-scalable algorithm?",
        "What is the difference between a serial and a parallel algorithm?",
        "What is the difference between a convex and a concave optimization algorithm?",
        "What is the difference between a batch and an online learning algorithm?",
        "What is the difference between a classification and a regression algorithm?",
        "What is the difference between a clustering and an association rule mining algorithm?",
        "What is the difference between a supervised and an unsupervised learning algorithm?",
        "What is the difference between a decision tree and a random forest algorithm?",
        "What is the difference between a support vector machine and a neural network algorithm?",
        "What is the difference between a gradient descent and a stochastic gradient descent algorithm?",
        "What is the difference between a breadth-first search and a depth-first search algorithm?",
        "What is the difference between a Dijkstra's algorithm and a Bellman-Ford algorithm?",
        "What is the difference between a Prim's algorithm and a Kruskal's algorithm?",
        "What is the difference between a quicksort and a mergesort algorithm?",
        "What is the difference between a bubble sort and a selection sort algorithm?",
        "What is the difference between a binary search and a linear search algorithm?",
        "What is the difference between a hill climbing and a simulated annealing algorithm?",
        "What is the difference between a tabu search and a genetic algorithm?",
        "What is the difference between a ant colony optimization and a particle swarm optimization algorithm?",
        "What is the difference between a backtracking and a branch-and-bound algorithm?",
        "What is the difference between a simplex and a dual simplex algorithm?",
        "What is the difference between a forward and a backward algorithm?",
        "What is the difference between a Viterbi and a Baum-Welch algorithm?",
        "What is the difference between a radix sort and a counting sort algorithm?",
        "What is the difference between a Newton's method and a Broyden's method algorithm?",
        "What is the difference between a PageRank and a HITS algorithm?",
        "What is the difference between a Johnson's algorithm and a Floyd-Warshall algorithm?",
        "What is the difference between a Boyer-Moore and a Knuth-Morris-Pratt algorithm?",
        "What is the difference between a Gale-Shapley and a Hungarian algorithm?",
        "What is the difference between a Euclidean and a Manhattan distance algorithm?",
        "What is the difference between a cosine and a Jaccard similarity algorithm?",
        "What is the difference between a Apriori and a FP-Growth algorithm?",
        "What is the difference between a RANSAC and a Hough transform algorithm?",
        "Python",
        "What is the output of 'hello' + 'world' in Python?",
        "What is the output of 5 * 3 in Python?",
        "What is the output of '5' + '3' in Python?",
        "What is the output of '5' * 3 in Python?",
        "What is the output of print(1, 2, 3) in Python?",
        "What is the output of print('1' + '2' + '3') in Python?",
        "What is the output of print(1 + 2 + 3) in Python?",
        "What is the output of print(1, 2, 3, sep=', ') in Python?",
        "What is the output of print(1, 2, 3, end='\\n') in Python?",
        "What is the output of print('hello', end='') followed by print('world') in Python?",
        "What is the output of a = 5; print(a) in Python?",
        "What is the output of a = 5; print(a + 3) in Python?",
        "What is the output of a = '5'; print(a * 3) in Python?",
        "What is the output of a = [1, 2, 3]; print(a[0]) in Python?",
        "What is the output of a = [1, 2, 3]; print(a[1]) in Python?",
        "What is the output of a = [1, 2, 3]; print(a[2]) in Python?",
        "What is the output of a = [1, 2, 3]; print(a[3]) in Python?",
        "What is the output of a = (1, 2, 3); print(a[0]) in Python?",
        "What is the output of a = (1, 2, 3); print(a[1]) in Python?",
        "What is the output of a = (1, 2, 3); print(a[2]) in Python?",
        "What is the output of a = (1, 2, 3); print(a[3]) in Python?",
        "What is the output of a = {'one': 1, 'two': 2, 'three': 3}; print(a['one']) in Python?",
        "What is the output of a = {'one': 1, 'two': 2, 'three': 3}; print(a['two']) in Python?",
        "What is the output of a = {'one': 1, 'two': 2, 'three': 3}; print(a['three']) in Python?",
        "What is the output of a = {'one': 1, 'two': 2, 'three': 3}; print(a['four']) in Python?",
        "What is the output of a = 5; b = 3; print(a + b) in Python?",
        "What is the output of a = 5; b = '3'; print(a + b) in Python?",
        "What is the output of a = '5'; b = 3; print(a + b) in Python?",
        "What is the output of a = '5'; b = '3'; print(a + b) in Python?",
        "snippets in JavaScript",
        "What is the output of console.log('hello' + 'world') in JavaScript?",
        "What is the output of console.log(5 * 3) in JavaScript?",
        "What is the output of console.log('5' + '3') in JavaScript?",
        "What is the output of console.log('5' * 3) in JavaScript?",
        "What is the output of console.log([1, 2, 3]) in JavaScript?",
        "What is the output of console.log({'one': 1, 'two': 2, 'three': 3}) in JavaScript?",
        "What is the output of console.log('hello', 'world') in JavaScript?",
        "What is the output of console.log(1, 2, 3) in JavaScript?",
        "What is the output of console.log('1' + '2' + '3') in JavaScript?",
        "What is the output of console.log(1 + 2 + 3) in JavaScript?",
        "What is the output of console.log(1, 2, 3, ',', ' ') in JavaScript?",
        "What is the output of console.log(1, 2, 3, '\\n') in JavaScript?",
        "What is the output of console.log('hello', '\n') followed by console.log('world') in JavaScript?",
        "What is the output of var a = 5; console.log(a) in JavaScript?",
        "What is the output of var a = 5; console.log(a + 3) in JavaScript?",
        "What is the output of var a = '5'; console.log(a * 3) in JavaScript?",
        "What is the output of var a = [1, 2, 3]; console.log(a[0]) in JavaScript?",
        "What is the output of var a = [1, 2, 3]; console.log(a[1]) in JavaScript?",
        "What is the output of var a = [1, 2, 3]; console.log(a[2]) in JavaScript?",
        "What is the output of var a = [1, 2, 3]; console.log(a[3]) in JavaScript?",
        "What is the output of var a = (1, 2, 3); console.log(a[0]) in JavaScript?",
        "What is the output of var a = (1, 2, 3); console.log(a[1]) in JavaScript?",
        "What is the output of var a = (1, 2, 3); console.log(a[2]) in JavaScript?",
        "What is the output of var a = (1, 2, 3); console.log(a[3]) in JavaScript?",
        "What is the output of var a = {'one': 1, 'two': 2, 'three': 3}; console.log(a['one']) in JavaScript?",
        "What is the output of var a = {'one': 1, 'two': 2, 'three': 3}; console.log(a['two']) in JavaScript?",
        "What is the output of var a = {'one': 1, 'two': 2, 'three': 3}; console.log(a['three']) in JavaScript?",
        "What is the output of var a = {'one': 1, 'two': 2, 'three': 3}; console.log(a['four']) in JavaScript?",
        "snippets in Java",
        "What is the output of System.out.println('hello' + 'world') in Java?",
        "What is the output of System.out.println(5 * 3) in Java?",
        "What is the output of System.out.println('5' + '3') in Java?",
        "What is the output of System.out.println('5' * 3) in Java?",
        "What is the output of System.out.println(Arrays.toString(new int[]{1, 2, 3})) in Java?",
        "What is the output of System.out.println(Arrays.toString(new String[]{'one': 1, 'two': 2, 'three': 3})) in Java?",
        "What is the output of System.out.println('hello' + '\n' + 'world') in Java?",
        "What is the output of System.out.println(1 + 2 + 3) in Java?",
        "What is the output of System.out.println('1' + '2' + '3') in Java?",
        "What is the output of System.out.println(1, 2, 3, ',', ' ') in Java?",
        "What is the output of System.out.println(1, 2, 3, '\\n') in Java?",
        "What is the output of System.out.println('hello' + '\\n'); System.out.println('world') in Java?",
        "What is the output of int a = 5; System.out.println(a) in Java?",
        "What is the output of int a = 5; System.out.println(a + 3) in Java?",
        "What is the output of String a = '5'; System.out.println(a * 3) in Java?",
        "What is the output of int[] a = {1, 2, 3}; System.out.println(a[0]) in Java?",
        "What is the output of int[] a = {1, 2, 3}; System.out.println(a[1]) in Java?",
        "What is the output of int[] a = {1, 2, 3}; System.out.println(a[2]) in Java?",
        "What is the output of int[] a = {1, 2, 3}; System.out.println(a[3]) in Java?",
        "What is the output of int[] a = (1, 2, 3); System.out.println(a[0]) in Java?",
        "What is the output of int[] a = (1, 2, 3); System.out.println(a[1]) in Java?",
        "What is the output of int[] a = (1, 2, 3); System.out.println(a[2]) in Java?",
        "What is the output of int[] a = (1, 2, 3); System.out.println(a[3]) in Java?",
        "What is the output of HashMap<String, Integer> a = new HashMap<>(); a.put('one', 1); System.out.println(a.get('one')) in Java?",
        "What is the output of HashMap<String, Integer> a = new HashMap<>(); a.put('two', 2); System.out.println(a.get('two')) in Java?",
        "What is the output of HashMap<String, Integer> a = new HashMap<>(); a.put('three', 3); System.out.println(a.get('three')) in Java?",
        "time complexity in JavaScript",
        "What is the time complexity of a for loop that iterates over an array of length n in JavaScript?",
        "What is the time complexity of an if statement in JavaScript?",
        "What is the time complexity of a function call in JavaScript?",
        "What is the time complexity of Array.prototype.slice() in JavaScript?",
        "What is the time complexity of Array.prototype.splice() in JavaScript?",
        "What is the time complexity of Array.prototype.concat() in JavaScript?",
        "What is the time complexity of Array.prototype.sort() in JavaScript?",
        "What is the time complexity of Array.prototype.includes() in JavaScript?",
        "What is the time complexity of Array.prototype.indexOf() in JavaScript?",
        "What is the time complexity of Array.prototype.lastIndexOf() in JavaScript?",
        "What is the time complexity of Array.prototype.push() in JavaScript?",
        "What is the time complexity of Array.prototype.pop() in JavaScript?",
        "What is the time complexity of Array.prototype.shift() in JavaScript?",
        "What is the time complexity of Array.prototype.unshift() in JavaScript?",
        "What is the time complexity of Object.keys() in JavaScript?",
        "What is the time complexity of Object.values() in JavaScript?",
        "What is the time complexity of Object.entries() in JavaScript?",
        "What is the time complexity of String.prototype.indexOf() in JavaScript?",
        "What is the time complexity of String.prototype.slice() in JavaScript?",
        "What is the time complexity of String.prototype.split() in JavaScript?",
        "What is the time complexity of String.prototype.charAt() in JavaScript?",
        "What is the time complexity of String.prototype.charCodeAt() in JavaScript?",
        "What is the time complexity of String.prototype.toUpperCase() in JavaScript?",
        "What is the time complexity of String.prototype.toLowerCase() in JavaScript?",
        "What is the time complexity of Math.max() in JavaScript?",
        "What is the time complexity of Math.min() in JavaScript?",
        "What is the time complexity of Math.random() in JavaScript?",
        "What is the time complexity of Math.floor() in JavaScript?",
        "What is the time complexity of Math.ceil() in JavaScript?",
        "What is the time complexity of Math.round() in JavaScript?",
        "What is the time complexity of Date.now() in JavaScript?",
        "What is the time complexity of Date.prototype.getTime() in JavaScript?",
        "What is the time complexity of Set.prototype.add() in JavaScript?",
        "What is the time complexity of Set.prototype.has() in JavaScript?",
        "What is the time complexity of Set.prototype.delete() in JavaScript?",
        "What is the time complexity of Map.prototype.set() in JavaScript?",
        "What is the time complexity of Map.prototype.get() in JavaScript?",
        "What is the time complexity of Map.prototype.has() in JavaScript?",
        "What is the time complexity of Map.prototype.delete() in JavaScript?",
        "What is the time complexity of Map.prototype.keys() in JavaScript?",
        "What is the time complexity of Map.prototype.values() in JavaScript?",
        "What is the time complexity of Map.prototype.entries() in JavaScript?",
        "What is the time complexity of a while loop that runs for n iterations in JavaScript?",
        "What is the time complexity of a do-while loop that runs for n iterations in JavaScript?",
        "What is the time complexity of a switch statement with n cases in JavaScript?",
        "What is the time complexity of a try-catch statement in JavaScript?",
        "What is the time complexity of a throw statement in JavaScript?",
        "What is the time complexity of a return statement in JavaScript?",
        "time complexity in Java", 
        "What is the time complexity of a for loop that iterates over an array of length n in Java?",
        "What is the time complexity of an if statement in Java?",
        "What is the time complexity of a function call in Java?",
        "What is the time complexity of Arrays.copyOf() in Java?",
        "What is the time complexity of Arrays.sort() in Java?",
        "What is the time complexity of Arrays.binarySearch() in Java?",
        "What is the time complexity of ArrayList.add() in Java?",
        "What is the time complexity of ArrayList.get() in Java?",
        "What is the time complexity of ArrayList.remove() in Java?",
        "What is the time complexity of LinkedList.add() in Java?",
        "What is the time complexity of LinkedList.get() in Java?",
        "What is the time complexity of LinkedList.remove() in Java?",
        "What is the time complexity of HashSet.add() in Java?",
        "What is the time complexity of HashSet.contains() in Java?",
        "What is the time complexity of HashSet.remove() in Java?",
        "What is the time complexity of HashMap.put() in Java?",
        "What is the time complexity of HashMap.get() in Java?",
        "What is the time complexity of HashMap.remove() in Java?",
        "What is the time complexity of HashMap.containsKey() in Java?",
        "What is the time complexity of HashMap.containsValue() in Java?",
        "What is the time complexity of PriorityQueue.offer() in Java?",
        "What is the time complexity of PriorityQueue.peek() in Java?",
        "What is the time complexity of PriorityQueue.poll() in Java?",
        "What is the time complexity of Stack.push() in Java?",
        "What is the time complexity of Stack.pop() in Java?",
        "What is the time complexity of Stack.peek() in Java?",
        "What is the time complexity of StringBuilder.append() in Java?",
        "What is the time complexity of StringBuilder.insert() in Java?",
        "What is the time complexity of String.indexOf() in Java?",
        "What is the time complexity of String.substring() in Java?",
        "What is the time complexity of String.replace() in Java?",
        "What is the time complexity of String.toCharArray() in Java?",
        "What is the time complexity of String.toLowerCase() in Java?",
        "What is the time complexity of String.toUpperCase() in Java?",
        "What is the time complexity of Math.min() in Java?",
        "What is the time complexity of Math.max() in Java?",
        "What is the time complexity of Math.abs() in Java?",
        "What is the time complexity of Math.ceil() in Java?",
        "What is the time complexity of Math.floor() in Java?",
        "What is the time complexity of Math.sqrt() in Java?",
        "What is the time complexity of Math.log() in Java?",
        "What is the time complexity of Math.exp() in Java?",
        "What is the time complexity of Math.pow() in Java?",
        "What is the time complexity of Collections.sort() in Java?",
        "What is the time complexity of Collections.binarySearch() in Java?",
        "What is the time complexity of Collections.reverse() in Java?",
        "What is the time complexity of Collections.rotate() in Java?",
        "What is the time complexity of Collections.shuffle() in Java?",
        "What is the time complexity of Collections.max() in Java?",
        "What is the time complexity of Collections.min() in Java?",
        "What is the time complexity of Arrays.stream() in Java?",
    
        Math.floor(Math.random()*10000) + " usd to inr",
        "squre root of " + Math.floor(Math.random()*10000),
        "factorial of " + Math.floor(Math.random()*10000) , 
        Math.floor(Math.random()*10000) + " meter to feet", 
        Math.floor(Math.random()*1000) + " / " + Math.floor(Math.random()*1000), 
        Math.floor(Math.random()*1000) + " * " + Math.floor(Math.random()*1000) , 
        Math.floor(Math.random()*10000) + " mile to kilometer" , 
        Math.floor(Math.random()*1000) + " inch to cm" 
    ];
    
    let searchIn = document.getElementById("sb_form_q");

    let submitIn = document.getElementById("sb_form_go");
    

    
    searchIn.value = itemSer[Math.floor(Math.random() * itemSer.length)] + " " + String.fromCharCode(Math.random() * (90 - 65) + 65) ;
    
    try{ submitIn.click(); } catch(e){}
    try{ document.forms[0].submit(); } catch(e){}
    

}
